# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param sigma the standard deviation used for the proposal distribution
#' @param x0 the initial value
#' @return a random sample of size N
#' @examples
#' \dontrun{
#' sigma <- 2
#' x0 <- 5
#' N <- 2000
#' rnC <- rwC(sigma, x0, N)
#' }
#' @export
rwC <- function(sigma, x0, N) {
    .Call('_StatComp20007_rwC', PACKAGE = 'StatComp20007', sigma, x0, N)
}

